
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 03 09:46:51 CST 2019
//----------------------------------------------------

package Controllers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALTERTABLE = 2;
  public static final int ICOR = 14;
  public static final int CCaracter = 20;
  public static final int FOREINGKEY = 10;
  public static final int CCOR = 15;
  public static final int ERROR = 21;
  public static final int IPAR = 17;
  public static final int COMA = 16;
  public static final int TituloCaracter = 19;
  public static final int EOF = 0;
  public static final int UNIQUE = 7;
  public static final int CONSTRAINT = 4;
  public static final int CPAR = 18;
  public static final int ADD = 3;
  public static final int error = 1;
  public static final int AFTER = 12;
  public static final int SPATIAL = 9;
  public static final int PRIMARYKEY = 6;
  public static final int Caracter = 5;
  public static final int INDEX = 13;
  public static final int FIRST = 11;
  public static final int FULLTEXT = 8;
}

